data: 
  leaf_tomato_disease_path: data/plantvillage/
  h5_train_features: data/preprocess/features_data.h5
  h5_train_labels: data/preprocess/labels_data.h5

final_variable:
  hog_bins_feature: 8
  seed: 10
  n_classes: 10
  num_trees: 100
  max_deep: 5
